apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: embymedia
  resources:
    requests:
      storage: "{{ .Values.mediasize }}"
