apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: embyconfig
  resources:
    requests:
      storage: "{{ .Values.configsize }}"
